#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

flake8 .

source .venv/bin/activate
set -a
source .env
set +a
python app/manage.py check
python app/manage.py migrate
python app/manage.py collectstatic --noinput

python app/manage.py runserver 0.0.0.0:8000